name = "taerim-clinic-web"
compatibility_date = "2026-04-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "taerimclinic_db"
database_id = "7f331e7f-a76c-4288-b67b-f5c7b10579e8"
preview_database_id = "7f331e7f-a76c-4288-b67b-f5c7b10579e8"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "taerimclinic-media"

[vars]
SITE_URL = "https://taerimclinic.com"
